In [9]:
import pandas as pd
import numpy as np

In [16]:
df= pd.read_csv('Sales Data - Raw_Data.csv')

In [17]:
df.shape

(50000, 9)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     50000 non-null  int64
 1   Order_Date   50000 non-null  object
 2   Customer_ID  49881 non-null  object
 3   Product      50000 non-null  object
 4   Category     49840 non-null  object
 5   Region       49870 non-null  object
 6   Quantity     49890 non-null  float64
 7   Revenue      49860 non-null  object
 8   Profit       49880 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 3.4+ MB

In [19]:
df.describe()

           Order_ID      Quantity
count  50000.000000  49890.000000
mean   26000.500000      4.017438
std    14433.901067      2.118410
min     1001.000000     -3.000000
25%    13500.750000      2.000000
50%    26000.500000      4.000000
75%    38500.250000      6.000000
max    51000.000000     30.000000

In [20]:
df.head(10)

,Order_ID,Order_Date,Customer_ID,Product,Category,Region,Quantity,Revenue,Profit
0,1001,02-05-2026,C406,Bookshelf,Furniture,Mumbai,2.0,18148,1536
1,1002,07-04-2026,C296,Air Purifier,Home,Mumbai,6.0,196692,32006
2,1003,07-01-2026,C827,Mouse,Electronics,Kolkata,3.0,"6,189 INR",1387
3,1004,27-04-2026,C050,Jeans,Apparel,Lucknow,1.0,5579,916
4,1005,01-05-2026,C205,Desk,Furniture,Bangalore,1.0,16301,2861
5,1006,21-03-2026,C585,Bookshelf,Furniture,Mumbai,5.0,65980,6049
6,1007,16-06-2026,NaN,Sofa,Furniture,Hyderabad,5.0,240240,47282
7,1008,27-02-2026,C512,Jeans,Apparel,Hyderabad,7.0,28651,5970
8,1009,06-02-2026,C167,Jeans,Apparel,Pune,1.0,5329,615
9,1010,29-04-2026,C784,Chair,Furniture,Chennai,2.0,25360,4151

In [21]:
df.tail(10)

,Order_ID,Order_Date,Customer_ID,Product,Category,Region,Quantity,Revenue,Profit
49990,50991,03-06-2026,C853,Air Purifier,Home,Kolkata,3.0,83556,16340
49991,50992,23-01-2026,C213,Sofa,Furniture,Kolkata,3.0,126669,27577
49992,50993,06-05-2026,C359,Chair,Furniture,Mumbai,5.0,57465,8980
49993,50994,11-04-2026,C517,Vacuum Cleaner,Home,Hyderabad,5.0,77825,7191
49994,50995,16-08-2026,C502,Vacuum Cleaner,Home,Lucknow,4.0,23504,1921
49995,50996,23-02-2026,C886,Backpack,Apparel,Delhi,2.0,3656,410
49996,50997,28-04-2026,C379,Vacuum Cleaner,Home,Chennai,6.0,31158,3711
49997,50998,12-02-2026,C073,Makeup Kit,Beauty,Chennai,5.0,19190,3078
49998,50999,10-02-2026,C212,Smartwatch,Electronics,Jaipur,2.0,37770,7312
49999,51000,17-07-2026,C590,Laptop,Electronics,Pune,4.0,292956,28330

In [22]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID    119
Product          0
Category       160
Region         130
Quantity       110
Revenue        140
Profit         120
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

#### Filling blank rows

#### Date Format

In [24]:
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    dayfirst=True,
    errors='coerce'
)
print(df['Order_Date'].dtype)

datetime64[ns]

In [25]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Month_Name'] = df['Order_Date'].dt.month_name()
df['Quarter'] = df['Order_Date'].dt.quarter
df['Day'] = df['Order_Date'].dt.day
df['Day_Name'] = df['Order_Date'].dt.day_name()

In [26]:
df[['Order_Date', 'Year', 'Month', 'Month_Name', 
   'Quarter', 'Day', 'Day_Name']].head()

  Order_Date  Year  Month Month_Name  Quarter  Day   Day_Name
0 2026-05-02  2026      5        May        2    2   Saturday
1 2026-04-07  2026      4      April        2    7    Tuesday
2 2026-01-07  2026      1    January        1    7  Wednesday
3 2026-04-27  2026      4      April        2   27     Monday
4 2026-05-01  2026      5        May        2    1     Friday

In [27]:
print(df.head(10))

   Order_ID Order_Date Customer_ID       Product     Category     Region  \
0      1001 2026-05-02        C406     Bookshelf    Furniture     Mumbai
1      1002 2026-04-07        C296  Air Purifier         Home     Mumbai
2      1003 2026-01-07        C827         Mouse  Electronics    Kolkata
3      1004 2026-04-27        C050         Jeans      Apparel    Lucknow
4      1005 2026-05-01        C205          Desk    Furniture  Bangalore
5      1006 2026-03-21        C585     Bookshelf    Furniture     Mumbai
6      1007 2026-06-16         NaN          Sofa    Furniture  Hyderabad
7      1008 2026-02-27        C512         Jeans      Apparel  Hyderabad
8      1009 2026-02-06        C167         Jeans      Apparel       Pune
9      1010 2026-04-29        C784         Chair    Furniture    Chennai

   Quantity    Revenue Profit  Year  Month Month_Name  Quarter  Day   Day_Name
0       2.0      18148   1536  2026      5        May        2    2   Saturday
1       6.0     196692  32006  2026      4      April        2    7    Tuesday
2       3.0  6,189 INR   1387  2026      1    January        1    7  Wednesday
3       1.0       5579    916  2026      4      April        2   27     Monday
4       1.0      16301   2861  2026      5        May        2    1     Friday
5       5.0      65980   6049  2026      3      March        1   21   Saturday
6       5.0     240240  47282  2026      6       June        2   16    Tuesday
7       7.0      28651   5970  2026      2   February        1   27     Friday
8       1.0       5329    615  2026      2   February        1    6     Friday
9       2.0      25360   4151  2026      4      April        2   29  Wednesday

In [28]:
df['Order_Date'].isna().sum()

np.int64(0)

##### Customer_ID

In [29]:
df['Customer_ID'] = df['Customer_ID'].fillna('Unknown')
print(df['Customer_ID'].head(30).isna())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: Customer_ID, dtype: bool

In [30]:
print(df['Customer_ID'].isnull().sum())

0

##### Category

In [31]:
df['Category'] = df['Category'].str.strip().str.title()
df['Category'] = df['Category'].fillna('Unknown')
print(df.iloc[100])

Order_ID                      1101
Order_Date     2026-01-22 00:00:00
Customer_ID                   C595
Product                 Headphones
Category                   Unknown
Region                      Jaipur
Quantity                       2.0
Revenue                       4646
Profit                         875
Year                          2026
Month                            1
Month_Name                 January
Quarter                          1
Day                             22
Day_Name                  Thursday
Name: 100, dtype: object

In [32]:
print(df['Category'].isnull().sum())

0

In [33]:
print(df.iloc[6])

Order_ID                      1007
Order_Date     2026-06-16 00:00:00
Customer_ID                Unknown
Product                       Sofa
Category                 Furniture
Region                   Hyderabad
Quantity                       5.0
Revenue                     240240
Profit                       47282
Year                          2026
Month                            6
Month_Name                    June
Quarter                          2
Day                             16
Day_Name                   Tuesday
Name: 6, dtype: object

##### Region

In [34]:
df['Region'] = df['Region'].str.strip().str.title()
df['Region'] = df['Region'].fillna('Unknown')
print(df)

       Order_ID Order_Date Customer_ID         Product     Category  \
0          1001 2026-05-02        C406       Bookshelf    Furniture
1          1002 2026-04-07        C296    Air Purifier         Home
2          1003 2026-01-07        C827           Mouse  Electronics
3          1004 2026-04-27        C050           Jeans      Apparel
4          1005 2026-05-01        C205            Desk    Furniture
...         ...        ...         ...             ...          ...
49995     50996 2026-02-23        C886        Backpack      Apparel
49996     50997 2026-04-28        C379  Vacuum Cleaner         Home
49997     50998 2026-02-12        C073      Makeup Kit       Beauty
49998     50999 2026-02-10        C212      Smartwatch  Electronics
49999     51000 2026-07-17        C590          Laptop  Electronics

          Region  Quantity    Revenue Profit  Year  Month Month_Name  Quarter  \
0         Mumbai       2.0      18148   1536  2026      5        May        2
1         Mumbai       6.0     196692  32006  2026      4      April        2
2        Kolkata       3.0  6,189 INR   1387  2026      1    January        1
3        Lucknow       1.0       5579    916  2026      4      April        2
4      Bangalore       1.0      16301   2861  2026      5        May        2
...          ...       ...        ...    ...   ...    ...        ...      ...
49995      Delhi       2.0       3656    410  2026      2   February        1
49996    Chennai       6.0      31158   3711  2026      4      April        2
49997    Chennai       5.0      19190   3078  2026      2   February        1
49998     Jaipur       2.0      37770   7312  2026      2   February        1
49999       Pune       4.0     292956  28330  2026      7       July        3

       Day   Day_Name
0        2   Saturday
1        7    Tuesday
2        7  Wednesday
3       27     Monday
4        1     Friday
...    ...        ...
49995   23     Monday
49996   28    Tuesday
49997   12   Thursday
49998   10    Tuesday
49999   17     Friday

[50000 rows x 15 columns]

In [35]:
print(df['Region'].isnull().sum())

0

##### Quantity

In [36]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
print(df['Quantity'].dtype)

float64

In [37]:
df[df['Quantity'] <= 0][
    ['Order_ID', 'Product', 'Category', 'Revenue', 'Profit', 'Quantity']
].head(20)

      Order_ID         Product     Category Revenue Profit  Quantity
405       1406         Monitor  Electronics  174784  33814      -3.0
484       1485  Vacuum Cleaner         Home  102130  17217      -3.0
663       1664          Camera  Electronics  328488  29686      -2.0
1111      2112        Keyboard  Electronics   18080   2960      -2.0
1113      2114        Backpack      Apparel   10704   2029      -1.0
1216      2217      Smartwatch  Electronics  179606  29553      -1.0
2043      3044      Makeup Kit       Beauty   10128   1584       0.0
2762      3763      Makeup Kit       Beauty   20673   4506       0.0
3083      4084       Bookshelf    Furniture   27840   6364       0.0
3317      4318           Chair    Furniture   36588   5556       0.0
3573      4574           Phone  Electronics  174705  15540      -3.0
4225      5226            Sofa    Furniture  168054  17887      -2.0
4538      5539          Camera  Electronics  274332  33795      -2.0
4582      5583      Makeup Kit       Beauty   26695   2737      -2.0
4820      5821      Makeup Kit       Beauty    7926   1369      -1.0
4891      5892        Keyboard  Electronics    4144    445       0.0
5299      6300          Camera  Electronics  181596  42104      -1.0
5782      6783           Chair    Furniture   22036   3928       0.0
6714      7715      Headphones  Electronics    8697   1269      -3.0
7090      8091        Keyboard  Electronics   37560   7742      -1.0

In [38]:
df.loc[df['Quantity'] <= 0, 'Quantity'] = np.nan

In [39]:
print("Missing Quantity:", df['Quantity'].isna().sum())

Missing Quantity: 251

In [77]:
df['Quantity'] = df.groupby('Product')['Quantity'].transform(
    lambda x: x.fillna(x.median())
)
df['Quantity'] = df['Quantity'].round().astype(int)
print(df.head(30))

    Order_ID Order_Date Customer_ID         Product     Category     Region  \
0       1001 2026-05-02        C406       Bookshelf    Furniture     Mumbai
1       1002 2026-04-07        C296    Air Purifier         Home     Mumbai
2       1003 2026-01-07        C827           Mouse  Electronics    Kolkata
3       1004 2026-04-27        C050           Jeans      Apparel    Lucknow
4       1005 2026-05-01        C205            Desk    Furniture  Bangalore
5       1006 2026-03-21        C585       Bookshelf    Furniture     Mumbai
6       1007 2026-06-16     Unknown            Sofa    Furniture  Hyderabad
7       1008 2026-02-27        C512           Jeans      Apparel  Hyderabad
8       1009 2026-02-06        C167           Jeans      Apparel       Pune
9       1010 2026-04-29        C784           Chair    Furniture    Chennai
10      1011 2026-06-22        C610            Desk    Furniture     Jaipur
11      1012 2026-01-08        C842      Headphones  Electronics  Bangalore
12      1013 2026-03-30        C344           Phone  Electronics    Lucknow
13      1014 2026-03-04        C394          Tablet  Electronics      Delhi
14      1015 2026-07-29        C173          Camera  Electronics    Kolkata
15      1016 2026-08-16        C858           Phone  Electronics  Hyderabad
16      1017 2026-07-26        C319          Laptop  Electronics  Bangalore
17      1018 2026-07-15        C485          Tablet  Electronics     Mumbai
18      1019 2026-06-13        C580          Tablet  Electronics  Bangalore
19      1020 2026-07-31        C254         Printer  Electronics  Bangalore
20      1021 2026-06-22        C349           Shoes      Apparel       Pune
21      1022 2026-04-05        C470      Smartwatch  Electronics      Delhi
22      1023 2026-05-25        C729           Mouse  Electronics    Chennai
23      1024 2026-06-14        C011           Mouse  Electronics  Bangalore
24      1025 2026-02-18        C494            Sofa    Furniture    Lucknow
25      1026 2026-03-27        C759          Tablet  Electronics       Pune
26      1027 2026-01-12        C084    Air Purifier         Home      Delhi
27      1028 2026-01-01        C344      Headphones  Electronics     Jaipur
28      1029 2026-04-04        C751  Vacuum Cleaner         Home    Lucknow
29      1030 2026-05-13        C095            Sofa    Furniture       Pune

    Quantity  Revenue   Profit  Year  Month Month_Name  Quarter  Day  \
0          2    18148   1536.0  2026      5        May        2    2
1          6   196692  32006.0  2026      4      April        2    7
2          3     6189   1387.0  2026      1    January        1    7
3          1     5579    916.0  2026      4      April        2   27
4          1    16301   2861.0  2026      5        May        2    1
5          5    65980   6049.0  2026      3      March        1   21
6          5   240240  47282.0  2026      6       June        2   16
7          7    28651   5970.0  2026      2   February        1   27
8          1     5329    615.0  2026      2   February        1    6
9          2    25360   4151.0  2026      4      April        2   29
10         6    57816   8680.0  2026      6       June        2   22
11         2    10850   2064.0  2026      1    January        1    8
12         5   294495  62926.0  2026      3      March        1   30
13         2    30704   3050.0  2026      3      March        1    4
14         2   163348  26638.0  2026      7       July        3   29
15         2    87312  15612.0  2026      8     August        3   16
16         2   162832  13188.0  2026      7       July        3   26
17         3   108918  22787.0  2026      7       July        3   15
18         5    77065  11534.0  2026      6       June        2   13
19         1     9617   1587.0  2026      7       July        3   31
20         1    11881   1051.0  2026      6       June        2   22
21         3    77757   8883.0  2026      4      April        2    5
22         5    18925   2406.0  2026      5        May        2   25
23         7    10311   1709.0  2026      6       June        2   14
24         6   173274  22357.0  2026      2   February        1   18
25         3    34095   5627.0  2026      3      March        1   27
26         5    58610   8044.0  2026      1    January        1   12
27         3    31923   3164.0  2026      1    January        1    1
28         7    48272  10697.0  2026      4      April        2    4
29         2   102370  20812.0  2026      5        May        2   13

     Day_Name
0    Saturday
1     Tuesday
2   Wednesday
3      Monday
4      Friday
5    Saturday
6     Tuesday
7      Friday
8      Friday
9   Wednesday
10     Monday
11   Thursday
12     Monday
13  Wednesday
14  Wednesday
15     Sunday
16     Sunday
17  Wednesday
18   Saturday
19     Friday
20     Monday
21     Sunday
22     Monday
23     Sunday
24  Wednesday
25     Friday
26     Monday
27   Thursday
28   Saturday
29  Wednesday

In [78]:
print("Missing Quantity:", df['Quantity'].isna().sum())
print("Zero Quantity:", (df['Quantity'] == 0).sum())
print("Negative Quantity:", (df['Quantity'] < 0).sum())

Missing Quantity: 0
Zero Quantity: 0
Negative Quantity: 0

##### Revenue

In [79]:
print(df['Revenue'].dtype)

Int64

In [80]:
df['Revenue'] = (
    df['Revenue']
    .astype('string')
    .str.strip()
    .str.replace(',', '', regex=False)
    .str.replace(r'\s*INR\s*', '', regex=True)
)
df['Revenue'].head(10)

0     18148
1    196692
2      6189
3      5579
4     16301
5     65980
6    240240
7     28651
8      5329
9     25360
Name: Revenue, dtype: string

In [87]:
df['Revenue'] = pd.to_numeric(
    df['Revenue'],
    errors='coerce'
).astype(float)
print(df['Revenue'].dtype)

float64

In [88]:
print("Missing Revenue:", df['Revenue'].isna().sum())

Missing Revenue: 0

In [89]:
df[df['Revenue'].isna()][
    ['Order_ID', 'Revenue', 'Product', 'Quantity', 'Profit']
].head(30)

Empty DataFrame
Columns: [Order_ID, Revenue, Product, Quantity, Profit]
Index: []

In [90]:
print("Minimum Revenue:", df['Revenue'].min())
print("Maximum Revenue:", df['Revenue'].max())

Minimum Revenue: 412.0
Maximum Revenue: 767935.0

In [91]:
print("Negative Revenue:", (df['Revenue'] < 0).sum())
print("Zero Revenue:", (df['Revenue'] == 0).sum())

Negative Revenue: 0
Zero Revenue: 0

In [92]:
df['Revenue'] = df.groupby('Product')['Revenue'].transform(
    lambda x: x.fillna(x.median())
)
df['Revenue'] = df['Revenue'].fillna(df['Revenue'].median())

In [94]:
print("Total Rows:", len(df))
print("Missing Revenue:", df['Revenue'].isna().sum())

Total Rows: 50000
Missing Revenue: 0

##### Profit

In [95]:
print(df['Profit'].dtype)

float64

In [96]:
df['Profit'] = pd.to_numeric(
    df['Profit'],
    errors='coerce'
)
print(df['Revenue'].dtype)

float64

In [97]:
print("Negative Profit:", (df['Profit'] < 0).sum())

Negative Profit: 0

In [98]:
print("Missing Profit:", df['Profit'].isna().sum())

Missing Profit: 420

In [99]:
df[df['Profit'].isna()][
    ['Order_ID', 'Product', 'Category', 'Region', 'Quantity', 'Revenue', 'Profit']
].head(20)

,Order_ID,Product,Category,Region,Quantity,Revenue,Profit
67,1068,Smartwatch,Electronics,Lucknow,5,97550.0,NaN
123,1124,Chair,Furniture,Kolkata,5,34715.0,NaN
287,1288,Keyboard,Electronics,Delhi,2,12610.0,NaN
349,1350,Camera,Electronics,Bangalore,1,80801.0,NaN
485,1486,Headphones,Electronics,Bangalore,4,22028.0,NaN
497,1498,Jeans,Apparel,Bangalore,5,15035.0,NaN
715,1716,Keyboard,Electronics,Ahmedabad,1,3346.0,NaN
755,1756,Printer,Electronics,Chennai,3,48492.0,NaN
1138,2139,Vacuum Cleaner,Home,Pune,5,96380.0,NaN
1307,2308,Jeans,Apparel,Jaipur,6,16680.0,NaN
1311,2312,Jeans,Apparel,Pune,7,16002.0,NaN
1458,2459,Jeans,Apparel,Mumbai,7,16226.0,NaN
1704,2705,Air Purifier,Home,Hyderabad,7,144683.0,NaN
1715,2716,Vacuum Cleaner,Home,Ahmedabad,1,11076.0,NaN
2026,3027,Air Purifier,Home,Ahmedabad,6,178194.0,NaN
2097,3098,Makeup Kit,Beauty,Chennai,5,9020.0,NaN
2179,3180,Smartwatch,Electronics,Kolkata,7,60249.0,NaN
2437,3438,Vacuum Cleaner,Home,Chennai,2,19092.0,NaN
2527,3528,Phone,Electronics,Lucknow,4,284052.0,NaN
2803,3804,Camera,Electronics,Hyderabad,5,244665.0,NaN

In [100]:
df['Profit'] = df.groupby('Product')['Profit'].transform(
    lambda x: x.fillna(x.median())
)
df['Profit'] = df['Profit'].fillna(df['Profit'].median())

In [101]:
print("Missing Profit:", df['Profit'].isna().sum())
print("Total Rows:", len(df))
print("Profit dtype:", df['Profit'].dtype)

Missing Profit: 0
Total Rows: 50000
Profit dtype: float64

In [102]:
print(df.isna().sum())

Order_ID       0
Order_Date     0
Customer_ID    0
Product        0
Category       0
Region         0
Quantity       0
Revenue        0
Profit         0
Year           0
Month          0
Month_Name     0
Quarter        0
Day            0
Day_Name       0
dtype: int64

In [103]:
df.to_csv("Cleaned_sales_dataset.csv", index=False)

In [104]:
import os
if os.path.exists("Cleaned_sales_dataset.csv"):
    print("Cleaned data file successfully saved!")
else:
    print("Cleaned data file not found!")

Cleaned data file successfully saved!